#spring.data.mongodb.uri=
#spring.data.mongodb.database=journaluser
#spring.data.mongodb.auto-index-creation=true


spring:
  data:
    mongodb:
      uri: mongodb+srv://sufyan:java123@cluster0.pnc5mhw.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaluser
      auto-index-creation: true


#servlet:
#  port: 8091

